- name: Application configuration tasks
  hosts: remote
  become: yes

  tasks:
    - include_vars: vars/common.yml
    - include_vars: vars/app.yml

    - name: Ensure Docker is running
      service:
        name: docker
        state: started

    - name: Copy local project to remote host
      synchronize:
        src: "{{PROJECT_LOCAL_DIR}}/."
        dest: "{{PROJECT_REMOTE_DIR}}"

    - name: Assign permissions for remote project to "{{USER}}"
      file: 
        path: "{{PROJECT_REMOTE_DIR}}"
        owner: "{{USER}}"
        group: "{{USER}}"
        mode: 0755

    - name: Build Docker image from Dockerfile
      docker_image: 
        name: "{{PROJECT_IMAGE_NAME}}"
        build:
          path: "{{PROJECT_REMOTE_DIR}}"
        source: build
        state: present

    - name: Tarball Docker image
      docker_image:
        name: "{{PROJECT_IMAGE_NAME}}"
        archive_path: "{{PROJECT_IMAGE_TARBALL}}"
        source: pull
        state: present

    - name: Load Docker tarball
      docker_image:
        name: "{{PROJECT_IMAGE_NAME}}"
        load_path: "{{PROJECT_IMAGE_TARBALL}}"
        source: load
        state: present

    - name: Deploy Docker image container
      docker_container:
        name: "{{PROJECT_IMAGE_NAME}}"
        image: "{{PROJECT_IMAGE_NAME}}"
        command: "sleep 1d"
        state: started


